name: Module Builder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Copy Readme & Changelog to src dir before zipping
        run: |
          cp "./README.md" "./src/lock-the-sheets/"
          cp "./CHANGELOG.md" "./src/lock-the-sheets/"

      - name: Zip Files
        working-directory: ./
        run: zip -r ./module.zip ./src/lock-the-sheets/*

      - name: Get Version
        shell: bash
        id: get-version
        run: echo "version=$(node ./.github/workflows/get-version.js)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: './module.zip, ./src/lock-the-sheets/module.json, ./README.md, ./CHANGELOG.md'
          tag: ${{ steps.get-version.outputs.version }}
